### ISSUE TITLE
Homepage navbar does not correctly switch active tab

### ISSUE THREAD

**Issue by joshghent** [maridco/marid-frontend#10]
After clicking 'All' then the active navigation item does not switch properly.

![ss 2015-01-27 at 07 15 42](https://cloud.githubusercontent.com/assets/2934976/5925770/e0d5d3f4-a65d-11e4-9b28-ea57a3193920.png)

**Comment by naveen09** [comment]
@joshghent  : I don't see this issue exists any more ! Not able to reproduce this.

**Comment by nb333** [comment]
@joshghent @naveen09 correct, this issue has been resolved. :)
