### ISSUE TITLE
Search bar does not render correctly 

### ISSUE THREAD

**Issue by joshghent** [maridco/marid-frontend#25]
Search bar does not render when page is reduced to < 750px in width.

**Comment by jpavlo** [comment]
i propose the solution that can be seen in develop branch to solve the problem Develop <750px in width

**Comment by joshghent** [comment]
@jpavlo Thanks for your work. Not quite what we were looking for. It's a great start so thanks :+1: 

If you are able to move it so it lies between the marid logo and the ||| menu on the right then I will merge those changes into master.
